#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright 2026 the cft-rebound contributors.
"""Write a v++ link configuration for N homogeneous cft_krnl tiles on the U50.

Derived, not typed. Compute unit t (1-based) master m (a=0 .. d=3) goes
to pseudo-channel HBM[4*(t-1) + m] - the rule cft-fp256's hw/link_quad.cfg
writes out in full for four tiles, and hw/link.cfg for one. One
pseudo-channel per master, exactly: the engine pipelines reads on a
single AXI ID with no reorder buffer, and a master that only ever talks
to one channel gets same-ID response ordering by construction (the
2026-08-30 audit in those files). The platform has 32 pseudo-channels,
so eight tiles is the wall, and an sp= line naming a shared channel
would not fail the link - it would quietly put the contention back -
which is why this is generated and checked rather than typed.

    python3 hw/gen_layout.py --tiles 5 --out build/link.cfg
    python3 hw/gen_layout.py --tiles 1 --check third_party/cft-fp256/hw/link.cfg
    python3 hw/gen_layout.py --tiles 4 --check third_party/cft-fp256/hw/link_quad.cfg

--check compares the CONNECTIVITY (nk= and sp= lines, order-insensitive
for sp=) of the generated layout against an existing file and exits 1 on
any difference, so the one- and four-tile cases can be held to the two
files cft-fp256 has actually linked and run.
"""
import argparse
import sys

HBM_PCS = 32
MASTERS = ("a", "b", "c", "d")
MAX_TILES = HBM_PCS // len(MASTERS)


def layout(tiles: int, kernel: str) -> str:
    if not 1 <= tiles <= MAX_TILES:
        raise SystemExit(f"--tiles {tiles}: the U50 has {HBM_PCS} HBM pseudo-channels "
                         f"and a tile takes {len(MASTERS)}, so 1..{MAX_TILES}")
    cus = [f"{kernel}_{t}" for t in range(1, tiles + 1)]
    out = [
        f"# {tiles} x {kernel} on the U50/U50C HBM platforms - GENERATED by",
        "# cft-rebound hw/gen_layout.py; regenerate rather than edit.",
        "#",
        "# Each compute unit has four AXI masters, one per operand stream, and",
        "# each master its own single pseudo-channel: CU t, master m ->",
        "# HBM[4(t-1)+m]. The reasons are cft-fp256's hw/link.cfg and",
        "# hw/link_quad.cfg (same-ID ordering by construction, 256 MB per",
        "# argument per tile, eight tiles hard).",
        "",
        "[connectivity]",
        f"nk={kernel}:{tiles}:{'.'.join(cus)}",
    ]
    for t, cu in enumerate(cus):
        for m, name in enumerate(MASTERS):
            out.append(f"sp={cu}.m_axi_{name}:HBM[{4 * t + m}]")
    return "\n".join(out) + "\n"


def connectivity(text: str):
    nk = None
    sp = set()
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("nk="):
            nk = s
        elif s.startswith("sp="):
            sp.add(s.replace(" ", ""))
    return nk, sp


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--tiles", type=int, required=True)
    ap.add_argument("--kernel", default="cft_krnl",
                    help="kernel name; libcft opens cft_krnl:{cft_krnl_N} by that "
                         "literal name, so anything else opens zero tiles")
    ap.add_argument("--out", help="write here (default: stdout)")
    ap.add_argument("--check", help="compare connectivity against this file; exit 1 if it differs")
    a = ap.parse_args()

    text = layout(a.tiles, a.kernel)
    if a.check:
        with open(a.check, encoding="utf-8") as f:
            want = connectivity(f.read())
        have = connectivity(text)
        if want != have:
            print(f"{a.check}: connectivity differs from a fresh {a.tiles}-tile layout",
                  file=sys.stderr)
            if want[0] != have[0]:
                print(f"  nk: file {want[0]!r}\n      gen  {have[0]!r}", file=sys.stderr)
            for s in sorted(want[1] - have[1]):
                print(f"  only in file: {s}", file=sys.stderr)
            for s in sorted(have[1] - want[1]):
                print(f"  only generated: {s}", file=sys.stderr)
            return 1
        print(f"ok: {a.check} has the {a.tiles}-tile connectivity")
        return 0
    if a.out:
        with open(a.out, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)
        print(f"wrote {a.out}: {a.tiles} x {a.kernel}, HBM[0..{4 * a.tiles - 1}]")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
