#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright 2026 the cft-rebound contributors.
#
# Emit IAS15's per-coordinate work as orbit-sequencer programs.
#
# Every operation of IAS15 except the gravity (which couples lanes) and
# the convergence test (a reduction over lanes) is elementwise over the
# 3N coordinates: one lane per coordinate, the same instruction stream
# for every lane, constants from the bank. That is the shape
# cft-fp256's sequencer and its 512-entry constant bank exist to run,
# and this file writes it down as .cfta text (docs/PROGRAMS.md of the
# pinned cft-fp256) so that cft-asm can assemble it and ias15_cft
# --engine program can run it through cft_program_run_ex.
#
# The programs use the FMA form of the scheme (--arith fma): no
# division, because a correctly rounded divide is not a sequencer
# program (cft-fp256's docs/ORBITS.md, obstacle 2). The constants are
# per-run data (BANK_EXT) because two of them depend on dt.
#
#   predict-<fmt>     x at substep n from b, a0, v0, x0, csx
#                     streams: a = x0, b = v0, c = a0
#                     scratch in: b0..b6, csx (8 slots)
#                     bank: K0..K6 = h_n (j+1)/(j+3) for j = 6..0,
#                           D2 = fl(dt h_n)/2, D1 = fl(dt h_n)
#                     deposit: x
#   correct<n>-<fmt>  the g and b update at substep n, n = 1..7
#                     streams: a = at (the acceleration at the substep)
#                     scratch in/out: a0, g0..g6, b0..b6, csb0..csb6 (22 slots)
#                     bank: R0..R_{n-1} = 1/rr, C0..C_{n-2} = c
#                     deposit: tmp = g_new - g_old (the convergence measure)
#
# The instruction order is exactly the host loop's in --arith fma
# mode; the check is that the two engines produce identical bits.

import os
import sys

here = os.path.dirname(os.path.abspath(__file__))
root = os.path.dirname(here)
outdir = os.path.join(root, "programs")

FORMATS = ["fp64", "fp128", "fp256"]

HEADER = """; %s - generated by tools/gen_programs.py, do not edit.
; SPDX-License-Identifier: GPL-3.0-or-later
; %s
"""


def predict(fmt):
    L = [HEADER % ("predict-" + fmt, "IAS15 position predictor at one substep, FMA form; see tools/gen_programs.py")]
    L.append(".format   %s" % fmt)
    L.append(".deposits 1")
    L.append(".bank     external")
    for i in range(7):
        L.append(".const    K%d" % i)
    L.append(".const    D2")
    L.append(".const    D1")
    L.append(".scratch  in 8")
    for i in range(7):
        L.append(".slot     B%d = %d" % (i, i))
    L.append(".slot     CSX = 7")
    L.append(".reg      x0 = r0")
    L.append(".reg      v0 = r1")
    L.append(".reg      a0 = r2")
    L.append(".reg      t  = r3")
    L.append(".reg      s  = r4")
    L.append("")
    L.append("ldl  t, B6")
    for i, j in enumerate(range(5, -1, -1)):
        L.append("ldl  s, B%d" % j)
        L.append("fma  t, t, K%d, s" % i)           # t = t*K_i + b_j
    L.append("fma  t, t, K6, a0")                   # + a0 level
    L.append("fma  t, t, D2, v0")                   # *dt*h/2 + v0
    L.append("mul  t, t, D1")                       # *dt*h
    L.append("ldl  s, CSX")
    L.append("sub  t, t, s")                        # xk = P - csx
    L.append("add  t, t, x0")                       # x = xk + x0
    L.append("deposit t")
    L.append("halt")
    return "\n".join(L) + "\n"


def predict_ens(fmt):
    """The predictor for an ensemble whose systems keep their own
    adaptive steps: fl(dt h_n) and its half are per LANE, so they ride
    in the scratch block (slots 8 and 9) instead of the bank, and the
    bank holds only the seven format-wide K constants. The arithmetic
    is instruction for instruction the same as predict()'s; the two
    constants are loaded into a register first."""
    L = [HEADER % ("predict-ens-" + fmt, "IAS15 position predictor at one substep, FMA form, per-lane dt; see tools/gen_programs.py")]
    L.append(".format   %s" % fmt)
    L.append(".deposits 1")
    L.append(".bank     external")
    for i in range(7):
        L.append(".const    K%d" % i)
    L.append(".scratch  in 10")
    for i in range(7):
        L.append(".slot     B%d = %d" % (i, i))
    L.append(".slot     CSX = 7")
    L.append(".slot     D2L = 8")
    L.append(".slot     D1L = 9")
    L.append(".reg      x0 = r0")
    L.append(".reg      v0 = r1")
    L.append(".reg      a0 = r2")
    L.append(".reg      t  = r3")
    L.append(".reg      s  = r4")
    L.append("")
    L.append("ldl  t, B6")
    for i, j in enumerate(range(5, -1, -1)):
        L.append("ldl  s, B%d" % j)
        L.append("fma  t, t, K%d, s" % i)           # t = t*K_i + b_j
    L.append("fma  t, t, K6, a0")                   # + a0 level
    L.append("ldl  s, D2L")
    L.append("fma  t, t, s, v0")                    # *dt*h/2 + v0, this lane's dt
    L.append("ldl  s, D1L")
    L.append("mul  t, t, s")                        # *dt*h
    L.append("ldl  s, CSX")
    L.append("sub  t, t, s")                        # xk = P - csx
    L.append("add  t, t, x0")                       # x = xk + x0
    L.append("deposit t")
    L.append("halt")
    return "\n".join(L) + "\n"


def add_cs(L, p, cs, inp, y, t, u):
    """Kahan's add_cs exactly as REBOUND writes it: y = inp - cs; t = p + y;
    cs = (t - p) - y; p = t. Registers p and cs are updated in place;
    p receives t through an exact copysign."""
    L.append("sub  %s, %s, %s" % (y, inp, cs))
    L.append("add  %s, %s, %s" % (t, p, y))
    L.append("sub  %s, %s, %s" % (u, t, p))
    L.append("sub  %s, %s, %s" % (cs, u, y))
    L.append("copysign %s, %s, %s" % (p, t, t))


def correct(fmt, n):
    L = [HEADER % ("correct%d-%s" % (n, fmt), "IAS15 corrector at substep %d, FMA form; see tools/gen_programs.py" % n)]
    L.append(".format   %s" % fmt)
    L.append(".deposits 1")
    L.append(".bank     external")
    for m in range(n):
        L.append(".const    RINV%d" % m)
    for m in range(n - 1):
        L.append(".const    COEF%d" % m)
    L.append(".scratch  in 22")
    L.append(".scratch  out 22")
    L.append(".slot     SLOT_A0 = 0")
    for m in range(7):
        L.append(".slot     G%d = %d" % (m, 1 + m))
    for m in range(7):
        L.append(".slot     B%d = %d" % (m, 8 + m))
    for m in range(7):
        L.append(".slot     CSB%d = %d" % (m, 15 + m))
    regs = {"at": "r0", "gk": "r3", "gkcs": "r4", "y": "r5", "t": "r6", "u": "r7", "a0": "r8",
            "q": "r9", "gm": "r10", "tmp": "r11", "prod": "r12", "bm": "r13", "csbm": "r14", "zero": "r15", "nega0": "r16"}
    for k, v in regs.items():
        L.append(".reg      %s = %s" % (k, v))
    L.append("")
    # gk = at; gk_cs = gravity_cs (+0); add_cs(gk, gk_cs, -a0); add_cs(gk, gk_cs, csa0 (+0))
    L.append("ldl  a0, SLOT_A0")
    L.append("neg  nega0, a0")
    L.append("copysign gk, at, at")          # gk = at; gkcs is r4, which starts at +0
    add_cs(L, "gk", "gkcs", "nega0", "y", "t", "u")
    add_cs(L, "gk", "gkcs", "zero", "y", "t", "u")   # csa0 is +0 with basic gravity
    # q = gk*R0; for m = 1..n-1: q = (q - g[m-1]) * R[m]
    L.append("mul  q, gk, RINV0")
    for m in range(1, n):
        L.append("ldl  gm, G%d" % (m - 1))
        L.append("sub  q, q, gm")
        L.append("mul  q, q, RINV%d" % m)
    # tmp = q - g_old; g[n-1] = q
    L.append("ldl  gm, G%d" % (n - 1))
    L.append("sub  tmp, q, gm")
    L.append("stl  q, G%d" % (n - 1))
    # b_m += tmp*C_m (compensated), m = 0..n-2; b_{n-1} += tmp
    for m in range(n - 1):
        L.append("ldl  bm, B%d" % m)
        L.append("ldl  csbm, CSB%d" % m)
        L.append("mul  prod, tmp, COEF%d" % m)
        add_cs(L, "bm", "csbm", "prod", "y", "t", "u")
        L.append("stl  bm, B%d" % m)
        L.append("stl  csbm, CSB%d" % m)
    L.append("ldl  bm, B%d" % (n - 1))
    L.append("ldl  csbm, CSB%d" % (n - 1))
    add_cs(L, "bm", "csbm", "tmp", "y", "t", "u")
    L.append("stl  bm, B%d" % (n - 1))
    L.append("stl  csbm, CSB%d" % (n - 1))
    L.append("deposit tmp")
    L.append("halt")
    return "\n".join(L) + "\n"


def main():
    os.makedirs(outdir, exist_ok=True)
    names = []
    for fmt in FORMATS:
        name = "predict-%s.cfta" % fmt
        with open(os.path.join(outdir, name), "w", newline="\n") as f:
            f.write(predict(fmt))
        names.append(name)
        name = "predict-ens-%s.cfta" % fmt
        with open(os.path.join(outdir, name), "w", newline="\n") as f:
            f.write(predict_ens(fmt))
        names.append(name)
        for n in range(1, 8):
            name = "correct%d-%s.cfta" % (n, fmt)
            with open(os.path.join(outdir, name), "w", newline="\n") as f:
                f.write(correct(fmt, n))
            names.append(name)
    print("wrote %d programs under %s" % (len(names), outdir))
    return 0


if __name__ == "__main__":
    sys.exit(main())
