#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright 2026 the cft-rebound contributors.
#
# A deterministic N-body problem of any size, for the body-count test.
#
# The reference problems in data/problems/ are physical: their numbers
# mean something and two of them are copied out of REBOUND's own
# examples. This one is not. It exists only to put N bodies in front of
# the integrator, so it is written to be (a) reproducible to the bit
# from N alone - no random number generator, no table - and (b) benign,
# so that what the test measures is the body count and not a close
# encounter.
#
#   a star of mass 1 at the origin, and N-1 bodies of mass 1e-6 on
#   circular coplanar orbits with semi-major axes spread linearly over
#   [1, 1 + (N-2)/32] and longitudes at successive golden angles, then
#   the whole system shifted into its barycentric frame.
#
# The golden angle is used because it is the standard way to place many
# points on a circle without any two of them lining up, which is what
# keeps the orbits from bunching; it is computed here from sqrt(5), not
# typed in. Circular velocities use mu = G(M* + m), which is the
# two-body value and therefore only approximately circular once all
# N-1 bodies pull on each other - that is fine and in fact desirable:
# a system slightly off its equilibrium exercises the step control.
#
# Python floats are IEEE binary64 with the same round-to-nearest-even
# arithmetic as C doubles on x86-64, so these are the bits a C program
# writing the same expressions would produce.
#
#   python tools/make_nbody.py N OUT.txt [--name NAME]

import argparse
import math
import sys


def hx(x):
    return float(x).hex()


def make(n):
    """Return (G, [(name, m, x, y, z, vx, vy, vz), ...]) for n bodies."""
    if n < 2:
        raise SystemExit("make_nbody: N must be at least 2")
    G = 1.0
    m_star = 1.0
    m_body = 1e-6
    # the golden angle, derived: 2*pi / phi**2 with phi = (1 + sqrt(5))/2
    phi = (1.0 + math.sqrt(5.0)) / 2.0
    golden = 2.0 * math.pi / (phi * phi)

    bodies = [["star", m_star, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]]
    for k in range(n - 1):
        a = 1.0 + k / 32.0
        th = golden * (k + 1)
        mu = G * (m_star + m_body)
        v = math.sqrt(mu / a)
        bodies.append(["b%d" % k, m_body,
                       a * math.cos(th), a * math.sin(th), 0.0,
                       -v * math.sin(th), v * math.cos(th), 0.0])

    # into the barycentric frame: subtract the mass-weighted mean of the
    # positions and velocities. Summed in the order the bodies are
    # written, so the result is reproducible.
    mtot = 0.0
    for b in bodies:
        mtot += b[1]
    for c in range(2, 8):
        s = 0.0
        for b in bodies:
            s += b[1] * b[c]
        s /= mtot
        for b in bodies:
            b[c] -= s
    return G, bodies


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("n", type=int)
    ap.add_argument("out")
    ap.add_argument("--name", default=None)
    args = ap.parse_args()
    name = args.name or ("nbody%d" % args.n)
    G, bodies = make(args.n)
    with open(args.out, "w", newline="\n") as f:
        f.write("# cft-rebound problem file, binary64 hex floats\n")
        f.write("# GENERATED by tools/make_nbody.py %d - a star and %d circular"
                " test bodies at golden-angle longitudes, barycentric\n"
                % (args.n, args.n - 1))
        f.write("name %s\n" % name)
        f.write("G %s\n" % hx(G))
        f.write("N %d\n" % len(bodies))
        for b in bodies:
            f.write("body %s %s %s %s %s %s %s %s\n"
                    % (b[0], hx(b[1]), hx(b[2]), hx(b[3]), hx(b[4]),
                       hx(b[5]), hx(b[6]), hx(b[7])))
    print("wrote %s: %d bodies" % (args.out, len(bodies)), file=sys.stderr)


if __name__ == "__main__":
    main()
